# whenever we push to master, CI-production workflow run
# and then, this workflow runs to publish new images to dockerhub

name: Publishing
on:
  push:
    branches:
    - 'master'
    - '!develop'

jobs:

  test_slips_in_docker:

    runs-on: ubuntu-latest
    env:
      SLIPS_VERSION: v0.8.4

    steps:

    # clone slips and checkout branch
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: stratosphereips
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


    # build slips from ubuntu dockerfile, but don't push
    - name: Build our ubuntu-dockerfile
      id: docker_build_slips
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./docker/ubuntu-image/Dockerfile
        tags: stratosphereips/slips:latest, stratosphereips/slips:${{ env.SLIPS_VERSION }}
        push: false

    # use the built image to run unit tests inside docker
    # we ignore the blocking module unit tests because we cannot run
    # docker with -cap-add=NET_ADMIN and use iptables in GH actions
    - name: Run unit tests inside docker
      uses: addnab/docker-run-action@v3
      with:
        image: stratosphereips/slips:latest
        run: |
          redis-server --daemonize yes
          python3 -m pytest tests/ --ignore="tests/test_dataset.py" --ignore="tests/test_blocking.py" -p no:warnings -vv
          python3 -m pytest tests/test_dataset.py -p no:warnings -vv -s

    # push one with the latest version as the tag, and another one with 'latest' as the tag
    - name: Push slips images to dockerhub
      env:
        slips_image: stratosphereips/slips:${{ env.SLIPS_VERSION }}
      run: |
        docker push $slips_image
        docker push stratosphereips/slips:latest

  build_and_push_dependency_image:

    runs-on: ubuntu-latest

    steps:

    # clone slips and checkout branch
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: stratosphereips
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push latest dependency image
      id: docker_build_dependency_image
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./docker/dependency-image/Dockerfile
        tags: stratosphereips/slips_dependencies:latest
        push: true